services:
  - type: web
    name: infinity-app
    env: node
    plan: free
    buildCommand: npm install ; npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: SERVE_FRONTEND
        value: true
      - key: FRONTEND_PATH
        value: ./frontend/dist
