services:
  - type: web
    name: infinity-app
    env: node
    plan: free
    buildCommand: npm install ; npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: SERVE_FRONTEND
        value: false
      - key: BACKEND_URL
        sync: false
      - key: CLIENT_URL
        sync: false
